version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  documentDB:
    image : davybello/mongo-replica-set:5.0.12
    container_name: documentdb
    volumes:
      - "./docker/.data/mongo1:/var/lib/mongo1"
      - "./docker/.data/mongo2:/var/lib/mongo2"
      - "./docker/.data/mongo3:/var/lib/mongo3"
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019

  documentdb-kafka-connect:
    image: globwizards/documentdb-messages-kafka-items-connect
    ports:
      - '8083:8083'
    depends_on:
      - kafka
      - documentDB
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_GROUP_ID: documentdb-kafka-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: documentdb-kafka-connect-group-config-storage
      CONNECT_OFFSET_STORAGE_TOPIC: documentdb-kafka-connect-group-offset-storage
      CONNECT_STATUS_STORAGE_TOPIC: documentdb-kafka-connect-group-status-storage
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: localhost:8083

      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"

  kafka-service:
    image: globwizards/kotlin-kafka-service
    container_name: kafka-service
    depends_on:
      - kafka
      - documentDB
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
      DB_HOST: 'documentDB'
      DB_USER: 'robot'
      DB_PSWD: 'tobor'
      DB_DATABASE: 'messages'
    ports:
      - '8080:8080'

volumes:
  mongodb4_data: