kafka:
  topics: 'items'

spring:
  data:
    mongodb:
#      host: ${DB_HOST:localhost}
#      port: ${DB_PORT:27017}
#      username: ${DB_USER:robot}
#      password: ${DB_PSWD:tobor}
      database: ${DB_DATABASE:messages}
      uri: mongodb://${DB_USER:robot}:${DB_PSWD:tobor}@${DB_HOST:localhost}:${DB_PORT:27017}/?authSource=admin&authMechanism=SCRAM-SHA-1

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: items-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false


