kafka:
  topics: 'items'

spring:
  data:
    mongodb:
      database: ${DB_DATABASE:messages}
#      uri: mongodb://shumyk:qwerty123@kotlin-kafka-mongo-cluster.chakvh9ud8we.eu-west-2.docdb.amazonaws.com:27017/?retryWrites=false&replicaSet=rs0
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
#      host: kotlin-kafka-mongo-cluster.chakvh9ud8we.eu-west-2.docdb.amazonaws.com
#      port: 27017
#      username: ${MONGO_USER:}
#      password: ${MONGO_PSWD:}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: items-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false


