apiVersion: v1
kind: Service
metadata:
  name: kotlin-kd-lb
  labels:
    type: kotlin-kd-lb
spec:
  type: LoadBalancer
  selector:
    type: kotlin-deployment
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
