#apiVersion: "apps/v1"
#kind: "Deployment"
#metadata:
#  name: "mongodb-deployment"
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      type: "mongodb-deployment"
#  strategy:
#    type: "RollingUpdate"
#    rollingUpdate:
#      maxSurge: 1
#      maxUnavailable: 1
#  minReadySeconds: 5
#  template:
#    metadata:
#      labels:
#        type: "mongodb-deployment"
#    spec:
#      containers:
#        - name: "mongo-db"
#          image: "mongo"
#          imagePullPolicy: "Always"
#          ports:
#            - containerPort: 27017
#              name: "mongodb"
#

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      type: "mongodb-deployment"
  template:
    metadata:
      labels:
        type: "mongodb-deployment"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: mongodb
          image: docker.io/mongo:4.2
          env:
          command: ["/bin/sh"]
          args: ["-c", "mongod --replSet=rs0 --bind_ip_all"]
          ports:
            - name: mongo-port
              containerPort: 27017


#apiVersion: apps/v1
#kind: StatefulSet
#metadata:
#  name: mongodb-replica
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: mongo
#  template:
#    metadata:
#      labels:
#        app: mongo
#        selector: mongo
#    spec:
#      terminationGracePeriodSeconds: 30
#      serviceAccount: mongo-account
#      containers:
#        - name: mongodb
#          image: docker.io/mongo:4.2
#          env:
#          command: ["/bin/sh"]
#          args: ["-c", "mongod --replSet=rs0 --bind_ip_all"]
#          resources:
#            limits:
#              cpu: 1
#              memory: 1500Mi
#            requests:
#              cpu: 1
#              memory: 1000Mi
#          ports:
#            - name: mongo-port
#              containerPort: 27017
#          volumeMounts:
#            - name: mongo-data
#              mountPath: /data/db
#  volumeClaimTemplates:
#    - metadata:
#        name: mongo-data
#      spec:
#        accessModes:
#          - ReadWriteOnce
#        resources:
#          requests:
#            storage: 10Gi