apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-kafka-connect-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: mongo-kafka-connect-deployment
  template:
    metadata:
      labels:
        type: mongo-kafka-connect-deployment
    spec:
      containers:
        - name: mongo-kafka-connect
          image: shumyk/mongo-kafka-connect
          ports:
            - containerPort: 8083
          env:
            - name: DB_USER
              value: shumyk
            - name: DB_PSWD
              value: password
            - name: DB_HOST
              value: kotlin-kafka-mongo-cluster.cluster-chakvh9ud8we.eu-west-2.docdb.amazonaws.com

            - name: CONNECT_BOOTSTRAP_SERVERS
              value: kafka-service:9092
            - name: KAFKA_OPTS
              value: " -Djavax.net.ssl.trustStore=/certs/rds-truststore.jks -Djavax.net.ssl.trustStorePassword=trustme"
            - name: CONNECT_GROUP_ID
              value: documentdb-kafka-connect-group
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: documentdb-kafka-connect-group-config-storage
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: documentdb-kafka-connect-group-offset-storage
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: documentdb-kafka-connect-group-status-storage
            - name: CONNECT_KEY_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: mongo-kafka-connect-service:8083
            - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
              value: "1"
