apiVersion: v1
kind: Service
metadata:
  name: mongo-kafka-connect-service
  labels:
    type: mongo-kafka-connect
spec:
  type: NodePort
  selector:
    type: mongo-kafka-connect-deployment
  ports:
    - port: 8083
      name: mongo-kafka-connect-port
      protocol: TCP
      targetPort: 8083