apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    type: mongodb
spec:
  type: NodePort
  selector:
    type: mongodb-deployment
  ports:
    - port: 27017
      name: mongodb-port
      protocol: TCP
      targetPort: 27017